"""Add 2 new columns 'created_at' & 'updated_at' in 2 tables 'users' & books

Revision ID: 086ee6396606
Revises: 16c6ea1fdfbf
Create Date: 2024-12-08 20:06:11.129158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086ee6396606'
down_revision = '16c6ea1fdfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.Date(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
