"""Add column 'book_img_url' to table 'borrow_records'

Revision ID: 435bc2494412
Revises: b42f873a27e8
Create Date: 2024-12-12 22:14:37.187750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435bc2494412'
down_revision = 'b42f873a27e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_img_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_records', schema=None) as batch_op:
        batch_op.drop_column('book_img_url')

    # ### end Alembic commands ###
