"""Add 3 columns 'user_name', 'user_email', 'book_title' to table 'borrow_records' & set nullable constraint for 'user_id', 'book_id'

Revision ID: b42f873a27e8
Revises: 086ee6396606
Create Date: 2024-12-11 18:06:32.028945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42f873a27e8'
down_revision = '086ee6396606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('user_email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('book_title', sa.String(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('book_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_records', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('book_title')
        batch_op.drop_column('user_email')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
